# Generated by Django 3.0.6 on 2020-05-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='description',
            field=models.TextField(default='NULL'),
        ),
    ]
