# Generated by Django 3.0.6 on 2020-05-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_headline_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='description',
            field=models.TextField(default='NULL', unique=True),
        ),
        migrations.AlterField(
            model_name='headline',
            name='image',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='headline',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='headline',
            name='url',
            field=models.TextField(unique=True),
        ),
    ]
